In [2]:
#drive mount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os #to define for file operation
from skimage.io import imread
from skimage.transform import resize

In [4]:
os.listdir('/content/drive/MyDrive/Data')

['Cat', 'Dog']

In [5]:
os.listdir('/content/drive/MyDrive/Data/Cat')

['cat.80.jpg',
 'cat.64.jpg',
 'cat.96.jpg',
 'cat.99.jpg',
 'cat.90.jpg',
 'cat.98.jpg',
 'cat.82.jpg',
 'cat.70.jpg',
 'cat.76.jpg',
 'cat.85.jpg',
 'cat.93.jpg',
 'cat.81.jpg',
 'cat.94.jpg',
 'cat.68.jpg',
 'cat.87.jpg',
 'cat.71.jpg',
 'cat.73.jpg',
 'cat.86.jpg',
 'cat.88.jpg',
 'cat.69.jpg',
 'cat.97.jpg',
 'cat.84.jpg',
 'cat.79.jpg',
 'cat.89.jpg',
 'cat.83.jpg',
 'cat.75.jpg',
 'cat.91.jpg',
 'cat.66.jpg',
 'cat.78.jpg',
 'cat.65.jpg',
 'cat.72.jpg',
 'cat.77.jpg',
 'cat.74.jpg',
 'cat.92.jpg',
 'cat.67.jpg',
 'cat.119.jpg',
 'cat.110.jpg',
 'cat.50.jpg',
 'cat.104.jpg',
 'cat.42.jpg',
 'cat.114.jpg',
 'cat.46.jpg',
 'cat.102.jpg',
 'cat.57.jpg',
 'cat.101.jpg',
 'cat.45.jpg',
 'cat.106.jpg',
 'cat.43.jpg',
 'cat.115.jpg',
 'cat.44.jpg',
 'cat.118.jpg',
 'cat.38.jpg',
 'cat.56.jpg',
 'cat.55.jpg',
 'cat.108.jpg',
 'cat.105.jpg',
 'cat.111.jpg',
 'cat.103.jpg',
 'cat.116.jpg',
 'cat.41.jpg',
 'cat.40.jpg',
 'cat.39.jpg',
 'cat.60.jpg',
 'cat.112.jpg',
 'cat.113.jpg',
 'cat.95.

In [6]:
os.listdir('/content/drive/MyDrive/Data/Dog')

['dog.58.jpg',
 'dog.65.jpg',
 'dog.3.jpg',
 'dog.61.jpg',
 'dog.17.jpg',
 'dog.52.jpg',
 'dog.21.jpg',
 'dog.56.jpg',
 'dog.32.jpg',
 'dog.2.jpg',
 'dog.41.jpg',
 'dog.48.jpg',
 'dog.60.jpg',
 'dog.31.jpg',
 'dog.46.jpg',
 'dog.24.jpg',
 'dog.44.jpg',
 'dog.18.jpg',
 'dog.67.jpg',
 'dog.59.jpg',
 'dog.5.jpg',
 'dog.13.jpg',
 'dog.33.jpg',
 'dog.49.jpg',
 'dog.22.jpg',
 'dog.55.jpg',
 'dog.20.jpg',
 'dog.1.jpg',
 'dog.7.jpg',
 'dog.54.jpg',
 'dog.8.jpg',
 'dog.51.jpg',
 'dog.11.jpg',
 'dog.35.jpg',
 'dog.25.jpg',
 'dog.62.jpg',
 'dog.10.jpg',
 'dog.27.jpg',
 'dog.43.jpg',
 'dog.23.jpg',
 'dog.38.jpg',
 'dog.39.jpg',
 'dog.63.jpg',
 'dog.53.jpg',
 'dog.12.jpg',
 'dog.14.jpg',
 'dog.47.jpg',
 'dog.37.jpg',
 'dog.6.jpg',
 'dog.29.jpg',
 'dog.30.jpg',
 'dog.42.jpg',
 'dog.36.jpg',
 'dog.26.jpg',
 'dog.19.jpg',
 'dog.15.jpg',
 'dog.28.jpg',
 'dog.64.jpg',
 'dog.57.jpg',
 'dog.16.jpg',
 'dog.66.jpg',
 'dog.9.jpg',
 'dog.34.jpg',
 'dog.50.jpg',
 'dog.68.jpg',
 'dog.4.jpg',
 'dog.40.jpg',
 'do

In [7]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [8]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))
#

68

In [9]:
#os
#path join
catpath=os.path.join('/content/drive/MyDrive/Data','Cat')
for i in os.listdir(catpath):
  print(i)
catpath

cat.80.jpg
cat.64.jpg
cat.96.jpg
cat.99.jpg
cat.90.jpg
cat.98.jpg
cat.82.jpg
cat.70.jpg
cat.76.jpg
cat.85.jpg
cat.93.jpg
cat.81.jpg
cat.94.jpg
cat.68.jpg
cat.87.jpg
cat.71.jpg
cat.73.jpg
cat.86.jpg
cat.88.jpg
cat.69.jpg
cat.97.jpg
cat.84.jpg
cat.79.jpg
cat.89.jpg
cat.83.jpg
cat.75.jpg
cat.91.jpg
cat.66.jpg
cat.78.jpg
cat.65.jpg
cat.72.jpg
cat.77.jpg
cat.74.jpg
cat.92.jpg
cat.67.jpg
cat.119.jpg
cat.110.jpg
cat.50.jpg
cat.104.jpg
cat.42.jpg
cat.114.jpg
cat.46.jpg
cat.102.jpg
cat.57.jpg
cat.101.jpg
cat.45.jpg
cat.106.jpg
cat.43.jpg
cat.115.jpg
cat.44.jpg
cat.118.jpg
cat.38.jpg
cat.56.jpg
cat.55.jpg
cat.108.jpg
cat.105.jpg
cat.111.jpg
cat.103.jpg
cat.116.jpg
cat.41.jpg
cat.40.jpg
cat.39.jpg
cat.60.jpg
cat.112.jpg
cat.113.jpg
cat.95.jpg
cat.59.jpg
cat.47.jpg
cat.58.jpg
cat.48.jpg
cat.49.jpg
cat.107.jpg
cat.61.jpg
cat.37.jpg
cat.35.jpg
cat.36.jpg
cat.100.jpg
cat.117.jpg
cat.53.jpg
cat.51.jpg
cat.63.jpg
cat.54.jpg
cat.52.jpg
cat.62.jpg
cat.109.jpg


'/content/drive/MyDrive/Data/Cat'

In [10]:
dogpath=os.path.join('/content/drive/MyDrive/Data','Dog')
for i in os.listdir(dogpath):
  print(i)
dogpath
#

dog.58.jpg
dog.65.jpg
dog.3.jpg
dog.61.jpg
dog.17.jpg
dog.52.jpg
dog.21.jpg
dog.56.jpg
dog.32.jpg
dog.2.jpg
dog.41.jpg
dog.48.jpg
dog.60.jpg
dog.31.jpg
dog.46.jpg
dog.24.jpg
dog.44.jpg
dog.18.jpg
dog.67.jpg
dog.59.jpg
dog.5.jpg
dog.13.jpg
dog.33.jpg
dog.49.jpg
dog.22.jpg
dog.55.jpg
dog.20.jpg
dog.1.jpg
dog.7.jpg
dog.54.jpg
dog.8.jpg
dog.51.jpg
dog.11.jpg
dog.35.jpg
dog.25.jpg
dog.62.jpg
dog.10.jpg
dog.27.jpg
dog.43.jpg
dog.23.jpg
dog.38.jpg
dog.39.jpg
dog.63.jpg
dog.53.jpg
dog.12.jpg
dog.14.jpg
dog.47.jpg
dog.37.jpg
dog.6.jpg
dog.29.jpg
dog.30.jpg
dog.42.jpg
dog.36.jpg
dog.26.jpg
dog.19.jpg
dog.15.jpg
dog.28.jpg
dog.64.jpg
dog.57.jpg
dog.16.jpg
dog.66.jpg
dog.9.jpg
dog.34.jpg
dog.50.jpg
dog.68.jpg
dog.4.jpg
dog.40.jpg
dog.45.jpg


'/content/drive/MyDrive/Data/Dog'

In [11]:
flatten_data=[]
target=[]
datadir='/content/drive/MyDrive/Data'
categories=['Cat','Dog']

In [12]:
for i in categories:
  path=os.path.join(datadir,i)
  print("loading")
  for  j in os.listdir(path):
    img_arr=imread(os.path.join(path,j))
    img_arr=resize(img_arr,(150,150,3))
    flatten_data.append(img_arr.flatten())
    target.append(categories.index(i))
  print("loading complte")


loading
loading complte
loading
loading complte


In [13]:
flatten_data=np.array(flatten_data)
target=np.array(target)

In [14]:
df=pd.DataFrame(flatten_data)
df['Target']=target
df

0         1         2         3         4         5         6  \
0    0.302291  0.294447  0.212094  0.305703  0.297860  0.215507  0.308719   
1    0.628178  0.526114  0.475343  0.633155  0.530634  0.485047  0.629232   
2    0.539947  0.487960  0.452266  0.484395  0.432404  0.396711  0.564937   
3    0.682918  0.659389  0.659388  0.662338  0.641749  0.632928  0.651718   
4    0.267715  0.216751  0.142193  0.271836  0.223559  0.140938  0.275575   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.240895  0.303640  0.260502  0.176969  0.239714  0.196577  0.294827   
149  0.339050  0.367841  0.423704  0.496663  0.514714  0.548421  0.471958   
150  0.602399  0.571027  0.527889  0.599512  0.568140  0.525003  0.594739   
151  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
152  0.058636  0.116703  0.181924  0.068429  0.124146  0.199747  0.070059   

            7         8         9  ...     67491     67492     67493  \
0    0.300876  0.218523  0.308718  ...  0.594982  0.579296  0.532237   
1    0.540237  0.496311  0.654336  ...  0.350163  0.288749  0.257374   
2    0.512943  0.477250  0.592547  ...  0.343699  0.338833  0.331202   
3    0.632111  0.620346  0.655147  ...  0.454645  0.332832  0.243040   
4    0.228515  0.139966  0.278628  ...  0.210044  0.202201  0.155142   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.357573  0.314435  0.502606  ...  0.924536  0.924536  0.924536   
149  0.488760  0.506873  0.425741  ...  0.616179  0.447552  0.310297   
150  0.563367  0.520230  0.591144  ...  0.158437  0.143170  0.147091   
151  0.223393  0.366578  0.169894  ...  0.093208  0.023828  0.017193   
152  0.124541  0.211015  0.077079  ...  0.385462  0.293878  0.185610   

        67494     67495     67496     67497     67498     67499  Target  
0    0.591976  0.576290  0.529231  0.588565  0.572879  0.525820       0  
1    0.358386  0.283197  0.266701  0.332954  0.272445  0.253367       0  
2    0.444647  0.385420  0.381104  0.514134  0.444042  0.415449       0  
3    0.210892  0.097412  0.041618  0.135869  0.034884  0.019520       0  
4    0.201097  0.193254  0.146195  0.200142  0.192299  0.145240       0  
..        ...       ...       ...       ...       ...       ...     ...  
148  0.924536  0.924536  0.924536  0.924536  0.924536  0.924536       1  
149  0.623240  0.454612  0.317357  0.612691  0.444063  0.306808       1  
150  0.159144  0.151301  0.155012  0.136559  0.136138  0.136349       1  
151  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556       1  
152  0.404742  0.310624  0.201493  0.408044  0.313926  0.204795       1  

[153 rows x 67501 columns]

In [15]:
df.shape

(153, 67501)

In [16]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

y

0      0
1      0
2      0
3      0
4      0
      ..
148    1
149    1
150    1
151    1
152    1
Name: Target, Length: 153, dtype: int64

In [17]:
X

0         1         2         3         4         5         6      \
0    0.302291  0.294447  0.212094  0.305703  0.297860  0.215507  0.308719   
1    0.628178  0.526114  0.475343  0.633155  0.530634  0.485047  0.629232   
2    0.539947  0.487960  0.452266  0.484395  0.432404  0.396711  0.564937   
3    0.682918  0.659389  0.659388  0.662338  0.641749  0.632928  0.651718   
4    0.267715  0.216751  0.142193  0.271836  0.223559  0.140938  0.275575   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.240895  0.303640  0.260502  0.176969  0.239714  0.196577  0.294827   
149  0.339050  0.367841  0.423704  0.496663  0.514714  0.548421  0.471958   
150  0.602399  0.571027  0.527889  0.599512  0.568140  0.525003  0.594739   
151  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
152  0.058636  0.116703  0.181924  0.068429  0.124146  0.199747  0.070059   

        7         8         9      ...     67490     67491     67492  \
0    0.300876  0.218523  0.308718  ...  0.527509  0.594982  0.579296   
1    0.540237  0.496311  0.654336  ...  0.277512  0.350163  0.288749   
2    0.512943  0.477250  0.592547  ...  0.376249  0.343699  0.338833   
3    0.632111  0.620346  0.655147  ...  0.364115  0.454645  0.332832   
4    0.228515  0.139966  0.278628  ...  0.149317  0.210044  0.202201   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.357573  0.314435  0.502606  ...  0.924536  0.924536  0.924536   
149  0.488760  0.506873  0.425741  ...  0.305655  0.616179  0.447552   
150  0.563367  0.520230  0.591144  ...  0.152137  0.158437  0.143170   
151  0.223393  0.366578  0.169894  ...  0.118748  0.093208  0.023828   
152  0.124541  0.211015  0.077079  ...  0.178427  0.385462  0.293878   

        67493     67494     67495     67496     67497     67498     67499  
0    0.532237  0.591976  0.576290  0.529231  0.588565  0.572879  0.525820  
1    0.257374  0.358386  0.283197  0.266701  0.332954  0.272445  0.253367  
2    0.331202  0.444647  0.385420  0.381104  0.514134  0.444042  0.415449  
3    0.243040  0.210892  0.097412  0.041618  0.135869  0.034884  0.019520  
4    0.155142  0.201097  0.193254  0.146195  0.200142  0.192299  0.145240  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.924536  0.924536  0.924536  0.924536  0.924536  0.924536  0.924536  
149  0.310297  0.623240  0.454612  0.317357  0.612691  0.444063  0.306808  
150  0.147091  0.159144  0.151301  0.155012  0.136559  0.136138  0.136349  
151  0.017193  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556  
152  0.185610  0.404742  0.310624  0.201493  0.408044  0.313926  0.204795  

[153 rows x 67500 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)


In [19]:
from sklearn.svm import SVC
s=SVC()
s.fit(X_train,y_train)

SVC()

In [20]:
y_pred=s.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0])

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.5434782608695652

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)


array([[22, 19],
       [ 2,  3]])

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           0       0.92      0.54      0.68        41
           1       0.14      0.60      0.22         5

    accuracy                           0.54        46
   macro avg       0.53      0.57      0.45        46
weighted avg       0.83      0.54      0.63        46



In [24]:
np='/content/drive/MyDrive/Data/Cat/cat.100.jpg'
img_arr=imread(np)
img_arr=resize(img_arr,(150,150,3))

In [28]:
actual_pd=s.predict(img_arr.flatten().reshape(1,-1))
actual_pd

array([0])

In [33]:
categories[actual_pd[0]]

'Cat'